[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target_version = ["py37", "py38", "py39", "py310"]

[tool.coverage.run]
branch = true
source = ["django_bootstrap5"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 120
skip_glob = "*/migrations/*.py"
known_first_party = ["django_bootstrap5"]
known_third_party = ["django"]
src_paths = ["*.py", "django_bootstrap5", "tests", "example"]
